
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\aliam\OneDrive\Desktop\build\assets\frame11")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1392x637")
window.configure(bg = "#E2A157")


canvas = Canvas(
    window,
    bg = "#E2A157",
    height = 637,
    width = 1392,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    211.0,
    62.0,
    anchor="nw",
    text="What is the correct structure of Phenol?",
    fill="#000000",
    font=("Inter", 48 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    323.0,
    257.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=154.0,
    y=245.0,
    width=46.0,
    height=58.0
)

canvas.create_text(
    164.0,
    441.0,
    anchor="nw",
    text="B.",
    fill="#000000",
    font=("Inter", 48 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    323.0,
    498.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    933.0,
    232.0,
    image=image_image_3
)

canvas.create_text(
    775.0,
    221.0,
    anchor="nw",
    text="C. ",
    fill="#000000",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    801.0,
    462.0,
    anchor="nw",
    text="D. ",
    fill="#000000",
    font=("Inter", 48 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1026.0,
    454.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
