
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\aliam\OneDrive\Desktop\build\assets\frame15")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1307x784")
window.configure(bg = "#B54444")


canvas = Canvas(
    window,
    bg = "#B54444",
    height = 784,
    width = 1307,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    207.0,
    68.0,
    anchor="nw",
    text="Evaluate 5*4! and express in simplest terms",
    fill="#000000",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    308.0,
    309.0,
    anchor="nw",
    text="B. 5!",
    fill="#000000",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    308.0,
    198.0,
    anchor="nw",
    text="A. 120",
    fill="#000000",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    311.0,
    419.0,
    anchor="nw",
    text="C. 20!",
    fill="#000000",
    font=("Inter", 48 * -1)
)
window.resizable(False, False)
window.mainloop()
